 #!/usr/bin/env python
import sys
import os
import math
import ROOT
from array import array

logdir = sys.argv[1:]
print logdir

c = ROOT.TCanvas('c', '', 800, 600)
c.SetFillColor(0)
c.SetFrameFillColor(0)
ROOT.gStyle.SetPadColor(0)
ROOT.gStyle.SetCanvasColor(0)
ROOT.gStyle.SetOptStat(0)
c.SetLeftMargin(0.15)
c.SetRightMargin(0.15)
c.SetTopMargin(0.1)
c.SetBottomMargin(0.15)
# c.SetLogy()
mg = ROOT.TMultiGraph("mg","")

# g_w28_pin  = ROOT.TGraph('0716/HPK-W28-PIN-L5P9-CV.csv', '-%lf,%*lf,%lf,-%*lf')
# g_w28_lgad = ROOT.TGraph('data/0716/HPK-W28-LGAD-L5P6-CV_doping.csv','-%lf,%*lf,%lf')
# g_w28_lgad = ROOT.TGraph('data/0728/HPK-W28-LGAD-L5P5-CV_doping.csv','-%lf,%*lf,%lf')
# g_w28_pin  = ROOT.TGraph('data/0716/HPK-W33-PIN-L5P9-CV_doping.csv', '-%lf,%*lf,%lf')
# g_w33_lgad = ROOT.TGraph('data/0716/HPK-W33-LGAD-L5P6-CV_doping.csv','-%lf,%*lf,%lf')
g_w33_lgad = ROOT.TGraph('data/0728/HPK-W33-LGAD-L5P5-CV_doping.csv','-%lf,%*lf,%lf')
# g_w33_pin  = ROOT.TGraph('data/0716/HPK-W33-PIN-L5P9-CV_doping.csv', '-%lf,%*lf,%lf')
# g_w37_lgad = ROOT.TGraph('data/0716/HPK-W37-LGAD-L5P6-CV_doping.csv','-%lf,%*lf,%lf')
g_w37_lgad = ROOT.TGraph('data/0728/HPK-W37-LGAD-L5P5-CV_doping.csv','-%lf,%*lf,%lf')
# g_w37_pin  = ROOT.TGraph('data/0716/HPK-W37-PIN-L5P9-CV_doping.csv', '-%lf,%*lf,%lf')
# g_w43_lgad = ROOT.TGraph('data/0713/HPK-W43-LGAD-L5P6-CV_doping.csv','-%lf,%*lf,%lf')
# g_w43_pin  = ROOT.TGraph('data/0713/HPK-W43-PIN-L5P9-CV_doping.csv', '-%lf,%*lf,%lf')

mg.Add(g_w28_lgad)
# mg.Add(g_w28_pin )
mg.Add(g_w33_lgad)
# mg.Add(g_w33_pin )
mg.Add(g_w37_lgad)
# mg.Add(g_w37_pin )
# mg.Add(g_w43_lgad)
# mg.Add(g_w43_pin )
mg.Draw('alp')

g_w28_lgad.SetLineWidth(2)
g_w28_lgad.SetLineColor(2)
g_w28_lgad.SetMarkerSize(1)
g_w28_lgad.SetMarkerColor(2)
g_w28_lgad.SetMarkerStyle(20)
# g_w28_pin.SetLineWidth(2)
# g_w28_pin.SetLineColor(2)
# g_w28_pin.SetLineStyle(2)
# g_w28_pin.SetMarkerSize(1)
# g_w28_pin.SetMarkerColor(2)
# g_w28_pin.SetMarkerStyle(24)
g_w33_lgad.SetLineWidth(2)
g_w33_lgad.SetLineColor(4)
g_w33_lgad.SetMarkerSize(1)
g_w33_lgad.SetMarkerColor(4)
g_w33_lgad.SetMarkerStyle(20)
# g_w33_pin.SetLineWidth(2)
# g_w33_pin.SetLineColor(4)
# g_w33_pin.SetLineStyle(2)
# g_w33_pin.SetMarkerSize(1)
# g_w33_pin.SetMarkerColor(4)
# g_w33_pin.SetMarkerStyle(24)
g_w37_lgad.SetLineWidth(2)
g_w37_lgad.SetLineColor(6)
g_w37_lgad.SetMarkerSize(1)
g_w37_lgad.SetMarkerColor(6)
g_w37_lgad.SetMarkerStyle(20)
# g_w37_pin.SetLineWidth(2)
# g_w37_pin.SetLineColor(6)
# g_w37_pin.SetLineStyle(2)
# g_w37_pin.SetMarkerSize(1)
# g_w37_pin.SetMarkerColor(6)
# g_w37_pin.SetMarkerStyle(24)
# g_w43_lgad.SetLineWidth(2)
# g_w43_lgad.SetLineColor(8)
# g_w43_lgad.SetMarkerSize(1)
# g_w43_lgad.SetMarkerColor(8)
# g_w43_lgad.SetMarkerStyle(20)
# g_w43_pin.SetLineWidth(2)
# g_w43_pin.SetLineColor(8)
# g_w43_pin.SetLineStyle(2)
# g_w43_pin.SetMarkerSize(1)
# g_w43_pin.SetMarkerColor(8)
# g_w43_pin.SetMarkerStyle(24)

mg.GetXaxis().SetTitle('Bias Voltage [V]')
mg.GetXaxis().SetTitleOffset(1.5)
mg.GetYaxis().SetTitle('Capacitance [pF]')
mg.GetYaxis().SetTitleOffset(1.5)
# mg.GetYaxis().SetRangeUser(0., 200)
legend = ROOT.TLegend(0.62, 0.5, 0.82, 0.88)
legend.AddEntry(g_w28_lgad, "W28 LGAD", "lp")
# legend.AddEntry(g_w28_pin , "W28 PIN", "lp")
legend.AddEntry(g_w33_lgad, "W33 LGAD", "lp")
# legend.AddEntry(g_w33_pin , "W33 PIN", "lp")
legend.AddEntry(g_w37_lgad, "W37 LGAD", "lp")
# legend.AddEntry(g_w37_pin , "W37 PIN", "lp")
# legend.AddEntry(g_w43_lgad, "W43 LGAD", "lp")
# legend.AddEntry(g_w43_pin , "W43 PIN", "lp")

legend.SetBorderSize(0)
legend.SetFillColor(0)
legend.Draw()

c.SaveAs('python/plots/doping.pdf')
# figfile = 'python/plots/graph_%s.pdf' %'_'.join(logdir)
# c.SaveAs(figfile)

